// Law content data from AGENTS.md - DO NOT ALTER

export const lawsData = [
  {
    id: 'mentalism',
    lawNumber: 1,
    title: 'LAW 1 — MENTALISM',
    hook: 'Your thinking sets the ceiling.',
    description: 'Clear mental models produce clean execution. Confusion creates rework and drift.',
    color: '#60A5FA', // Blue
    colorClass: 'laws-mentalism',
    videoSrc: '/videos/mentalism.mp4',
    thumbnailSrc: '/thumbnails/mentalism-thumb.png',
    audioSrc: '/audio/mentalism-pod.m4a',
    infographicSrc: '/infographics/mentalism-info.png',
    questions: [
      "What is the single most important outcome you want in the next 90 days?",
      "What decision are you stuck on right now?",
      "What's the biggest time leak in your business today?",
    ],
    submitLabel: 'Save my Mentalism answers',
  },
  {
    id: 'correspondence',
    lawNumber: 2,
    title: 'LAW 2 — CORRESPONDENCE',
    hook: 'Internal order shows up externally.',
    description: 'Culture, operations, and leadership habits always express as outcomes.',
    color: '#818CF8', // Indigo
    colorClass: 'laws-correspondence',
    videoSrc: '/videos/correspondence.mp4',
    thumbnailSrc: '/thumbnails/correspondence-thumb.png',
    audioSrc: '/audio/correspondence-pod.m4a',
    infographicSrc: '/infographics/correspondence-info.png',
    questions: [
      "What problem do you keep tolerating that you know you shouldn't?",
      "Where does work slow down most (handoffs, unclear ownership, communication, conflict)?",
      "If your business was fully aligned, what would customers notice first?",
    ],
    submitLabel: 'Save my Correspondence answers',
  },
  {
    id: 'vibration',
    lawNumber: 3,
    title: 'LAW 3 — VIBRATION',
    hook: 'Everything is in motion.',
    description: 'Nothing rests. Energy, momentum, and attention all fluctuate. Managing frequency and intensity prevents burnout and sustains performance.',
    color: '#A78BFA', // Purple
    colorClass: 'laws-vibration',
    videoSrc: '/videos/vibration.mp4',
    thumbnailSrc: '/thumbnails/vibration-thumb.png',
    audioSrc: '/audio/vibration-pod.m4a',
    infographicSrc: '/infographics/vibration-info.png',
    questions: [
      'What energy level does your business operate at most of the time (high stress, steady flow, low momentum)?',
      'Where do you feel the most friction or resistance right now?',
      'What would it take to shift the frequency to something more sustainable?',
    ],
    submitLabel: 'Save my Vibration answers',
  },
  {
    id: 'polarity',
    lawNumber: 4,
    title: 'LAW 4 — POLARITY',
    hook: 'Opposites are connected.',
    description: 'Every challenge contains its solution. Growth and pain coexist. Understanding polarity transforms problems into opportunities.',
    color: '#F472B6', // Pink
    colorClass: 'laws-polarity',
    videoSrc: '/videos/polarity.mp4',
    thumbnailSrc: '/thumbnails/polarity-thumb.png',
    audioSrc: '/audio/polarity-pod.m4a',
    infographicSrc: '/infographics/polarity-info.png',
    questions: [
      'What problem are you facing that might actually contain the solution?',
      'Where are you stuck between two extremes (fast vs slow, control vs trust, push vs pause)?',
      'What would shift if you stopped resisting the opposite?',
    ],
    submitLabel: 'Save my Polarity answers',
  },
  {
    id: 'rhythm',
    lawNumber: 5,
    title: 'LAW 5 — RHYTHM',
    hook: 'Success moves in cycles.',
    description: 'Growth and recovery are both required. Ignoring cycles causes burnout and instability.',
    color: '#FB7185', // Rose
    colorClass: 'laws-rhythm',
    videoSrc: '/videos/rhythm.mp4',
    thumbnailSrc: '/thumbnails/rhythm-thumb.png',
    audioSrc: '/audio/rhythm-pod.m4a',
    infographicSrc: '/infographics/rhythm-info.png',
    questions: [
      'What season are you in right now: build, stabilize, scale, repair, or reset?',
      'What feels most overextended (cashflow, delivery, team capacity, leadership attention)?',
      'What would you stop for 30 days to regain control?',
    ],
    submitLabel: 'Save my Rhythm answers',
  },
  {
    id: 'cause_effect',
    lawNumber: 6,
    title: 'LAW 6 — CAUSE & EFFECT',
    hook: 'Results are delayed decisions.',
    description: 'Outcomes are feedback. Ownership accelerates learning and improvement.',
    color: '#FBBF24', // Amber
    colorClass: 'laws-causeEffect',
    videoSrc: '/videos/cause-effect.mp4',
    thumbnailSrc: '/thumbnails/cause-effect-thumb.png',
    audioSrc: '/audio/cause-effect-pod.m4a',
    infographicSrc: '/infographics/cause-effect-info.png',
    questions: [
      "What outcome are you getting that you don't want?",
      "What do you believe is the root cause (best guess)?",
      "What's one small change you could make this week that would shift the result?",
    ],
    submitLabel: 'Save my Cause & Effect answers',
  },
  {
    id: 'gender',
    lawNumber: 7,
    title: 'LAW 7 — GENDER',
    hook: 'Creation requires complementary forces.',
    description: 'Vision and execution must work together or the business stalls.',
    color: '#34D399', // Emerald
    colorClass: 'laws-gender',
    videoSrc: '/videos/gender.mp4',
    thumbnailSrc: '/thumbnails/gender-thumb.png',
    audioSrc: '/audio/gender-pod.m4a',
    infographicSrc: '/infographics/gender-info.png',
    questions: [
      'What valuable idea is stuck and not implemented?',
      'What keeps it stuck (no owner, unclear next step, time, fear, no system)?',
      'If you could delegate 80%, what would you keep vs hand off?',
    ],
    submitLabel: 'Save my Gender answers',
  },
]

// Section IDs for analytics tracking
export const sectionIds = {
  hero: 'hero',
  alignment: 'alignment',
  receive: 'receive',
  tutorial: 'tutorial',
  howItWorks: 'how-it-works',
  mentalism: 'mentalism',
  correspondence: 'correspondence',
  vibration: 'vibration',
  polarity: 'polarity',
  rhythm: 'rhythm',
  causeEffect: 'cause-effect',
  gender: 'gender',
  deepening: 'deepening',
  contact: 'contact',
}
